language: node_js
node_js:
   - "0.10"
   - "0.11"
   - "0.12"
   - "io.js"
after_success:
   - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=l7r9zxJgsKfkmkmHxXL5zzQ3ASwckm8Go node_modules/.bin/builder -c test --coverage --coveralls
