language: node_js
node_js:
   - "0.11"
   - "0.10"
after_success:
   - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=S3JTQo3V9oqnmfFTq8jhqehUumgTdim3u node_modules/.bin/alinex-make -c test --coverage --coveralls