language: node_js
node_js:
   - "0.10"
   - "0.11"
   - "0.12"
after_success:
   - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=Tr2iOjmiqviAd6xnfp9eOSHJD3PIGqtQN node_modules/.bin/builder -c test --coverage --coveralls
